/**
 * Auto-updater public API. Main-process only; dynamically imported from app-startup
 * when `isAutoUpdaterEnabled()` is true, so the OSS code path never pulls in
 * electron-updater or its transitive deps.
 *
 * All platforms use native electron-updater (generic provider). The manual
 * path (manual-manifest.ts) is kept as fallback for non-AppImage Linux where
 * electron-updater cannot auto-install, but it's excluded from the primary
 * checkForUpdates path.
 *
 * initUpdater() THROWS on real init failure (lazy import / setFeedURL) so the
 * caller can skip installing the "Check for Updates…" menu.
 *
 * Split across ./state (module state + getUpdateState/setOnUpdateDownloaded),
 * ./store (daily-check throttle), ./listeners (event handlers), ./versioning
 * (pure semver/YAML helpers), and ./manual-manifest (non-AppImage-Linux orchestrator).
 */

import type { AppUpdater } from 'electron-updater';
import { app, BrowserWindow, dialog } from 'electron';
import fs from 'fs';
import path from 'path';
import { getFeedUrl } from './feed-config';
import { registerAutoUpdaterListeners } from './listeners';
import { log } from './logger';
import { checkForUpdatesManual } from './manual-manifest';
import { isTrustedUpdateInfo } from './origin';
import { getDownloadedVersion, setMainWindow, setUserCheckInFlight } from './state';
import { recordCheckedNow, shouldAutoCheck } from './store';

export { shouldAutoCheck } from './store';
export { getUpdateState, setOnUpdateDownloaded } from './state';

let _autoUpdater: AppUpdater | null = null;
async function lazyAutoUpdater(): Promise<AppUpdater> {
  if (!_autoUpdater) {
    const mod = (await import('electron-updater')) as typeof import('electron-updater') & {
      default?: { autoUpdater?: AppUpdater };
    };
    const namedAutoUpdater = Object.prototype.hasOwnProperty.call(mod, 'autoUpdater')
      ? mod.autoUpdater
      : undefined;
    const autoUpdater = namedAutoUpdater ?? mod.default?.autoUpdater;
    if (!autoUpdater) {
      throw new Error('electron-updater autoUpdater export unavailable');
    }
    _autoUpdater = autoUpdater;
  }
  return _autoUpdater;
}

export async function initUpdater(window: BrowserWindow): Promise<void> {
  setMainWindow(window);

  // Defensive — caller should gate on isAutoUpdaterEnabled(), but bail if somehow invoked without URL.
  if (!getFeedUrl()) {
    return;
  }

  // Non-AppImage Linux cannot auto-install via electron-updater; manual path
  // handles those from the menu. Native path still works for AppImage.
  if (process.platform === 'linux' && !process.env.APPIMAGE) {
    return;
  }

  try {
    const autoUpdater = await lazyAutoUpdater();
    // autoDownload is controlled by user setting — default true, but can be
    // toggled in Settings > General > Updates. When false, the update-available
    // listener shows a dialog but does NOT auto-download.
    autoUpdater.autoDownload = true;
    autoUpdater.autoInstallOnAppQuit = true;

    if (!app.isPackaged) {
      // electron-updater refuses to emit events in dev unless a dev-app-update.yml
      // exists and forceDevUpdateConfig is set. Write one so dev-mode end-to-end works.
      const appPath = app.getAppPath();
      fs.mkdirSync(appPath, { recursive: true });
      fs.writeFileSync(
        path.join(appPath, 'dev-app-update.yml'),
        `provider: generic\nurl: ${getFeedUrl()}\n`,
      );
      autoUpdater.forceDevUpdateConfig = true;
    }

    // Generic provider with default 'latest' channel fetches:
    //   - Windows NSIS: latest.yml (generated by electron-builder)
    //   - macOS:        latest-mac.yml
    //   - Linux AppImage: latest-linux.yml
    autoUpdater.setFeedURL({ provider: 'generic', url: getFeedUrl() });

    registerAutoUpdaterListeners(autoUpdater, quitAndInstall);
  } catch (err) {
    throw err;
  }
}

export async function checkForUpdates(silent: boolean): Promise<void> {
  // Defensive double-gate: if the URL was cleared after init, bail.
  if (!getFeedUrl()) {
    return;
  }

  // Non-AppImage Linux uses manual path (electron-updater cannot auto-install deb/tar).
  if (process.platform === 'linux' && !process.env.APPIMAGE) {
    const arch: 'x64' | 'arm64' = process.arch === 'arm64' ? 'arm64' : 'x64';
    await checkForUpdatesManual(silent, 'linux', arch);
    return;
  }

  try {
    setUserCheckInFlight(!silent);
    const autoUpdater = await lazyAutoUpdater();
    const result = await autoUpdater.checkForUpdates();
    if (result?.updateInfo && !isTrustedUpdateInfo(result.updateInfo, getFeedUrl())) {
      return;
    }
    recordCheckedNow();
  } catch (err: unknown) {
    setUserCheckInFlight(false);
    const message = err instanceof Error ? err.message : String(err);
    if (!silent) {
      dialog.showErrorBox('Update Check Failed', message);
    }
    log('ERROR', '[Updater] checkForUpdates failed', { err: message });
  }
}

export async function quitAndInstall(): Promise<void> {
  const autoUpdater = await lazyAutoUpdater();
  // isSilent=false: show OS restart UI on Windows; isForceRunAfter=true: relaunch after install.
  // app.quit() fires internally → before-quit handler runs shutdownApp() (see main/index.ts).
  autoUpdater.quitAndInstall(false, true);
}

export function autoCheckForUpdates(): void {
  // Double-gate mirrors checkForUpdates — protects against the menu firing a check
  // when the URL has been cleared or is not configured.
  if (!getFeedUrl()) {
    return;
  }
  if (!shouldAutoCheck()) {
    return;
  }
  void checkForUpdates(true);
}
